WebBooks/urls.py
# Listing 9.13
from django.contrib import admin
from django.urls import path
from catalog import views
from django.urls import re_path


urlpatterns = [
    path('', views.index, name='index'),
    path('authors_add/', views.authors_add, name='authors_add'),
    path('edit1/<int:id>/', views.edit1, name='edit1'),
    path('create/', views.create, name='create'),
    path('delete/<int:id>/', views.delete, name='delete'),
#    path('admin/', admin.site.urls),
    #re_path(r'control/', admin.site.urls, name='control'),
    re_path(r'control/', admin.site.urls, name='control'),
    re_path(r'^blyadbook/$', views.BookListView.as_view(), name='blyadbook'),
    re_path(r'^book/(?P<pk>\d+)$', views.MyBookDetailView.as_view(), name='book-detail'),
    re_path(r'^authors/$', views.AuthorListView.as_view(), name='authors'),

]

# Listing 10.3
from django.urls import path, include

# Добавление URL-адреса для входа в систему
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += [
    re_path(r'^mybooks/$', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
]

# Listing 10.38
urlpatterns += [
    re_path(r'^book/create/$', views.BookCreate.as_view(), name='book_create'),
    re_path(r'^book/update/(?P<pk>\d+)$', views.BookUpdate.as_view(), name='book_update'),
    re_path(r'^book/delete/(?P<pk>\d+)$', views.BookDelete.as_view(), name='book_delete'),
]

catalog/models.py
#from audioop import reverse
from django.urls import reverse
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User
from datetime import date

class Genre(models.Model):
    name = models.CharField(max_length=200,
                            help_text=" Введите жанр книги",
                            verbose_name="Жaнp книги")

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=20,
                            help_text=" Введите язык книги",
                            verbose_name="Язык книги")
    def __str__(self):
        return self.name



class Author(models.Model):
    first_name = models.CharField(max_length=100,
                                  help_text="Введите имя автора",
                                  verbose_name="Имя автора")
    last_name = models.CharField(max_length=100,
                                 help_text="Введите фамилию автора",
                                 verbose_name="Фамилия автора")
    date_of_birth = models.DateField(
                        help_text="Введите дату рождения",
                        verbose_name="Дaтa рождения",
                        null=True, blank=True)
    date_of_death = models.DateField(
                        help_text="Введите дату смерти",
                        verbose_name="Дaтa смерти",
                        null=True, blank=True)

    def __str__(self):
        return f"{self.first_name}"
        #return self.name


class Book(models.Model):
    title = models.CharField(max_length=200,
                             help_text="Введите название книги",
                             verbose_name="Название книги")
    genre = models.ForeignKey('Genre', on_delete=models.CASCADE,
                              help_text=" Выберите жанр для книги",
                              verbose_name="Жaнp книги", null=True)
    language = models.ForeignKey('Language',
                                 on_delete=models.CASCADE,
                                 help_text="Выберите язык книги",
                                 verbose_name="Язык книги", null=True)
    author = models.ManyToManyField('Author',
                                    help_text="Выберите автора книги",
                                    verbose_name="Aвтop книги")
    summary = models.TextField(max_length=1000,
                               help_text="Введите краткое описание книги",
                               verbose_name="Аннотация книги")
    isbn = models.CharField(max_length=13,
                            help_text="Должно содержать 13 символов",
                            verbose_name="ISBN книги")
#def get_absolute_url(self):
    # Возвращает URL-aдpec для доступа к определенному экземпляру книги.
   # breakpoint()
    #return reverse('book-detail', args=[str(self.id)])
    #return reverse('book-detail', kwargs={"pk": model.pk})
    #return reverse('book-detail', kwargs={'pk': self.id})
    #return 1

#на html странице book_list не возвращает url ссылку

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # Возвращает url-адрес для доступа к определенному экземпляру книги.
        return reverse('book-detail', args=[self.id])


def display_author(self):
    return ', '.join([author.last_name for author in self.author.all()])

    display_author.short_description = 'Авторы'

class Status(models.Model):
    name = models.CharField(max_length=20,
                            help_text="Введите статус экземпляра книги",
                            verbose_name="Cтaтyc экземпляра книги")
    def __str__(self):
        return self.name

class Bookinstance(models.Model):
        book = models.ForeignKey('Book', on_delete=models.CASCADE, null=True)
        inv_nom = models.CharField(max_length=20, null=True,
                                   help_text="Введите инвентарный номер экземпляра",
                                   verbose_name="Инвентарный номер")
        imprint = models.CharField(max_length=200,
                                   help_text="Введите издательство и год выnуска",
                                   verbose_name="Издательство")
        status = models.ForeignKey('Status', on_delete=models.CASCADE,
                                   null=True,
                                   help_text='Изменить состояние экземпляра',
                                   verbose_name = "Cтaтyc экземпляра книги")
        due_back = models.DateField(null=True, blank=True,
                                    help_text="Введите конец срока статуса",
                                    verbose_name="Дaтa окончания статуса")
        borrower = models.ForeignKey(User, on_delete=models.SET_NULL,
                                     null=True, blank=True,
                                     verbose_name="Заказчик",
                                     help_text='Выберите заказчика книги')

        @property
        def is_overdue(self):
            if self.due_back and date.today() > self.due_back:
                return True
            return False


        def __str__(self):
            return '%s %s %s' % (self.inv_nom, self.book, self.status)

catalog/forms.py
from django import forms
from datetime import date
from django.forms import ModelForm
from .models import Book


class AuthorsForm(forms.Form):
    first_name = forms.CharField(label="Имя автора")
    last_name = forms.CharField(label="Фамилия автора")
    date_of_birth = forms.DateField(label="Дата рождения",
                                    initial=format(date.today()),
                                    widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    date_of_death = forms.DateField(label="Дата смерти",
                                    initial=format(date.today()),
                                    widget=forms.widgets.DateInput(attrs={'type': 'date'}))

class BookModelForm(ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'genre', 'language', 'author', 'summary', 'isbn']

catalog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Book, Author, Bookinstance, Genre
from django.views import generic
from django.views.generic import ListView, DetailView
from django.contrib import admin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import *
from django.shortcuts import render
from .forms import AuthorsForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Book


class BookCreate(CreateView):
    model = Book
    fields = '__all__'
    success_url = reverse_lazy('blyadbook')
    template_name = "book_form.html"

class BookUpdate(UpdateView):
    model = Book
    fields = '__all__'
    success_url = reverse_lazy('blyadbook')
    template_name = "book_form.html"

class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('blyadbook')
    template_name = "book_confirm_delete.html"

# получение данных из БД и загрузка шаблона authors_add.html
def authors_add(request):
        allauthor = Author.objects.all()
        authorsform = AuthorsForm()
        return render(request, "catalog/authors_add.html", {"form": authorsform, "allauthor": allauthor})


# Listing 10.28
# сохранение данных об авторах в БД
def create(request):
     if request.method == "POST":
            author = Author()
            author.first_name = request.POST.get("first_name")
            author.last_name = request.POST.get("last_name")
            author.date_of_birth = request.POST.get("date_of_birth")
            author.date_of_death = request.POST.get("date_of_death")
            author.save()
            return HttpResponseRedirect("/authors_add/")


# Listing 10.29
# удаление авторов из БД
def delete(request, id):
    try:
        author = Author.objects.get(id=id)
        author.delete()
        return HttpResponseRedirect("/authors_add/")
    except Author.DoesNotExist:
        return HttpResponseNotFound("<h2>Автор не найден</h2>")


# Listing 10.30
# изменение данных в БД
def edit1(request, id):
    error = ""
    author = Author.objects.get(id=id)


    if request.method == "POST":
            author.first_name = request.POST.get("first_name")
            author.last_name = request.POST.get("last_name")
            author.date_of_birth = request.POST.get("date_of_birth")
            author.date_of_death = request.POST.get("date_of_death")
            if author.date_of_birth != "" and author.date_of_death != "":
                author.save()
                return HttpResponseRedirect("/authors_add/")
            else:
                # return HttpResponse("Заполните поля с датами")
                #messages.error(request, 'username or password not correct')
                error = "Заполните поля с датами"
                return render(request, "catalog/edit1.html", {"author": author, "error": error})
    else:
        return render(request, "catalog/edit1.html", {"author": author, "error": error})





class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """
    Универсальный класс представления списка книг,
    находящихся в заказе у текущего пользователя.
    """
    model = Bookinstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='2').order_by('due_back')


class BookListView(ListView):
        model = Book
        template_name = 'catalog/book_list1.html'
        paginate_by = 3
        #context_object_name = 'Book'

class MyBookDetailView(DetailView):
      model = Book
     # pk_url_kwarg = "id"
      template_name = 'catalog/My_book_detail.html'
      context_object_name = 'My_book'


class AuthorListView(ListView):
    model = Author
    paginate_by = 4

# Create your views here.
#def index(request):
 #   return HttpResponse("Глaвнaя страница сайта Мир книг!")

#def test(request):
 #    book_title = Book.title
  #   return render(request, 'book_detail.html', context = {'book_title': book_title}
#                        )

def huinana(request):
    return 1



def book_list_view(request):
        book_list=Book.objects.all()
        return render(request, "book_list.html", context = {'book_list': book_list}, )

def show_book(request, id):
    try:
        book = Book.objects.get(id=id)
        book_title = book.title
        return render(request, "book_detail.html", {"book_title": book_title})
    except Book.DoesNotExist:
        return HttpResponseNotFound("<h2> не найден</h2>")

def My_admin(request):
       return admin.site.urls

def index(request):
    #Генерация "количеств" некоторых главных объектов
    num_books = Book.objects.all().count()
    num_instances = Bookinstance.objects.all().count()
    # Доступные книги (статус= 'На складе')
    # Здесь метод 'all()' применен по умолчанию.
    num_instances_available = Bookinstance.objects.filter(status__exact=2).count()
    # Авторы книг,
    num_authors = Author.objects.count()
    # Отрисовка НТМL-шаблона index.html с данными
    # внутри переменной context
    SESSION_SAVE_EVERY_REQUEST = True
    # Количество посещений этого view, подсчитанное
    # в переменной session
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    return render(request, 'index.html',
                            context={'num_books': num_books,
                                     'num_instances': num_instances,
                                     'num_instances_available': num_instances_available,
                                     'num_authors': num_authors,
                                     'num_visits':num_visits},
                 )

catalog/templates/catalog/My_book_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Название книги: {{ My_book.title }}</h1>
  <p><strong>Жaнp:</strong> {{ My_book.genre }}</p>
  <p><strong>Аннотация:</strong> {{ My_book.summary }} </p>
  <p><strong>ISBN:</strong> {{ My_book.isbn }}</р>
  <p><strong>Язык:</strong> {{ My_book.language }}</р>
  <ul>
    {% for author in My_book.author.all%}
    <li>
        <p><strong>Aвтop:</strong>
          <a href="">  {{ author.first_name }}"
                {{author.last_name}}</a> </p>
    </li>
    {% endfor %}
  </ul>



 <div style="margin-left:20px;margin-top:20px">
    <h4>Количество экземпляров книг в БД</h4>
    {% for copy in My_book.bookinstance_set.all %}
    <hr><p class="{% if copy.status == 1 %} text-success
                  {% elif copy.status == 2 %} text-danger
                  {% else %} text-warning
                  {% endif %}"> {{ copy.get_status_display }}</p>
        <p><strong>Издaтeльcтвo:</strong> {{copy.imprint}}</p>
        <p class="text-muted"><strong>Инвeнтapный нoмep:</strong> {{copy.inv_nom}}</p>
        <p><strong>Cтaтyc экземпляра книги в БД:</strong>  {{copy.status}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Список авторов в БД</h1>

   {% if author_list %}
       {% for author in author_list.all %}
        <p>{{ author.first_name}}  {{author.last_name}},
           <strong>Родился-</strong>{{author.date_of_birth}},
           <strong>Умер-</strong>{{author.date_of_death}}</p>
      {% endfor %}
   {% else %}
      <p>В базе данных нет авторов</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/authors_add.html
{% extends "base_generic.html" %}
{% block content %}

  <h3>Список авторов в БД</h3>
   <table>
        <thead><th>Id</th><th>----Имя----
                       </th><th>Фамилия</th><th></th></thead>
  {% if allauthor %}
     {% for allauthor in allauthor.all %}
        <tr>
           <td>{{allauthor.id}}</td>
           <td>{{allauthor.first_name}}</td>
           <td>{{allauthor.last_name}}</td>
           <td>{{allauthor.date_of_birth}}</td>
           <td><a href="/edit1/{{allauthor.id}}">Изменить</a> ,
               <a href="/delete/{{allauthor.id}}">Удалить</a></td>
        </tr>
     {% endfor %}
  {% else %}
      <p>В базе данных нет авторов</p>
  {% endif %}
    </table>

<h3>Добавить в БД автора книги</h3>
<form method="POST" action="/create/">
        {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <input type="submit" value="Сохранить" >
</form>
{% endblock %}

catalog/templates/catalog/book_list.html
s{% extends "base_generic.html" %}

{% block content %}
    <h1>Список книг в БД</h1>
    {% if book_list %}
    <ul>
      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">
                 {{ book.title }}</a>
                 ({{book.genre}})
        <a href="/book/update/{{book.id}}">Изменить</a> ,
        <a href="/book/delete/{{book.id}}">Удалить</a>
      </li>
      {% endfor %}
    </ul>
    {% else %}
      <p>В базе данных нет книг</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/bookinstance_list_Ьorrowed_user.html
<-- Listing 10.21-->
{% extends "base_generic.html" %}

{% block content %}
    <h1>Взятые книги</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}
                                   text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">
                                {{bookinst.book.title}}</a>
                         ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>Нет книг со статусом В ЗАКАЗЕ.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/edit1.html
<-- Listing 10.31-->
{% extends "base_generic.html" %}
{% block content %}

  <h3>Список авторов в БД</h3>
  <h4>{{author.first_name}} {{author.last_name}} {{author.date_of_birth}}</h4>

    <form method="POST">
        {% csrf_token %}


        <p> <label>Измените дату рождения</label><br>
            <input type="date" placeholder="DD-MM-YYYY" name="date_of_birth" value= "{{author.date_of_birth}}" required about="сука"/>
        </p>

        <p> <label>Измените имя</label><br>
            <input type="text" name="first_name"
                   value="{{author.first_name}}" />
        </p>
        <p> <label>Измените фамилию</label><br>
            <input type="text" name="last_name"
                   value="{{author.last_name}}" />
        </p>
        <p> <label>Измените дату смерти</label><br>
            <input type="date" name="date_of_death"
                   value="{{author.date_of_death}}" />
        </p>

        {{error}} <br>

        <input type="submit" value="Сохранить" >
    </form>

{% endblock %}

catalog/templates/catalog/oldbook_list.html
{% extends "base_generic.html" %}




{% block content %}
  <h1>Список книг в БД</h1>
  {% if book_list %}
  <ul>
      {% for book in book_list %}
          <li>
              <!-- <a href="{{ book.get_absolute_url }}"> -->
              <a href="{{ views.huinana }}">
               <!--<a href=1>--->
                  {{ book.title }}
                 {{ book.get_absolute_url }}</a>
                        ({{ book.genre }})
              ({{ views.huinana }})

          </li>
            <tr><td>{{ book.title }}</td>
                <td><a href="show_book/{{book.id}}">инфо</a></td> <br>
            </tr>
      {% endfor %}
  </ul>
  {% else %}
        <p>В базе данных нет книг</p>
  {% endif %}
{% endblock %}